sudo: required
language: c
os:
  - linux

before_install:
  - sudo apt-get install check

before_script:  
    - cmake .

script: 
	- make 
	- make test

after_success:
	- bash <(curl -s https://codecov.io/bash)
